# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

jobs:
- job: Default
  timeoutInMinutes: 360
  pool:
    vmImage: windows-latest
  variables:
    solution: 'Source/TemplatesVsix/TemplatesVsix.sln'
    buildConfiguration: 'Release'
    vsixPath: 'Source/TemplatesVsix/CognibaseTemplates/bin/$(buildConfiguration)/CognibaseTemplates.vsix'
    nupkgName: 'Missionware.Cognibase.Templates'
    nupkgOutput: 'Output'
    #version.Patch: $[counter(variables['version.MajorMinor'], 0)]
    versionNumber: '$(version.MajorMinorPatch)'
    versionNumberWithPrefix: 'CbTemplates_v$(versionNumber)'
    nupkgPathWithVersion: '$(nupkgOutput)/$(nupkgName).$(versionNumber).nupkg'
  
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        if ([string]::IsNullOrWhitespace(${env:VERSION_MAJORMINORPATCH})) { throw "version.MajorMinorPatch variable not set in pipeline variables. Set it to *.* (eg 1.2)" }
        Write-Host "##vso[build.updatebuildnumber]TEMPLATES_v$(versionNumber)_$($env:Build_BuildNumber)"
    displayName: '* Version $(versionNumber) *'

  - task: NuGetToolInstaller@1
    displayName: 'Nuget install'  

  - task: CmdLine@2
    inputs:
      script: 'Scripts\build_template.bat $(versionNumber)'
    displayName: 'build template nupkg'

  - task: CmdLine@2
    inputs:
      script: 'Scripts\vsix_convert_eula_to_rtf.bat'
    displayName: 'Copy EULA to VSIX '

  - task: CmdLine@2
    inputs:
      script: 'Scripts\vsix_convert_readme_to_html.bat'
    displayName: 'Copy readme to VSIX'

  - task: PowerShell@2
    inputs:
      filePath: 'fix-versions.ps1'
      arguments: '$(versionNumber)'
    displayName: 'Set version in VSIX'



  - task: VSBuild@1
    inputs:
      solution: $(solution)
    displayName: 'Build VSIX solution'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'push'
      packagesToPush: '$(nupkgPathWithVersion)'
      nuGetFeedType: 'internal'
      publishVstsFeed: '9d0932d4-4f72-46fc-a079-0aa8ebef7fd8/1ef3ca01-e917-4c7f-8c59-f68c69d28c58'
      arguments: '--skip-duplicate'
    displayName: 'push to Core feed'